name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - master
    - main
    - develop

jobs:
  pre-commit:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3
      with:
        extra_args: --hook-stage manual --all-files
    - name: Run PyLint
      run: |
        echo "::add-matcher::$GITHUB_WORKSPACE/.github/matchers/pylint.json"
        pipx run nox -s pylint

  checks:
    name: Check Python ${{ matrix.python-version }} on ${{ matrix.sys.os }}
    runs-on: ${{ matrix.sys.os }}
    needs: [pre-commit]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.10"]
        sys:
          - { os: ubuntu-latest, shell: bash }
          - { os: macos-latest, shell: bash }
          - { os: windows-latest, shell: 'msys2 {0}' }

        include:
        - python-version: pypy-3.7
          sys: { os: ubuntu-latest, shell: bash }

    defaults:
      run:
        shell: ${{ matrix.sys.shell }}

    steps:
    - uses: actions/checkout@v2

    - uses: msys2/setup-msys2@v2
      if: matrix.sys.os == 'windows-latest'
      with:
        update: true
        install: >-
          autotool
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-python-pip
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-make
          mingw-w64-x86_64-python-pytest

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install build tools (macos-latest)
      if: matrix.sys.os == 'macos-latest'
      run: brew install autoconf automake libtool

    - name: Install package
      run: python -m pip install -e .[test]

    - name: Test package
      run: python -m pytest -ra
